(defun emacs-random-acronym ()
  (let ((list '(
			    "Escape-Meta-Alt-Control-Shift"
			    "Eight Megabytes And Constantly Swapping"
			    "Even a Master of Arts Comes Simpler"
			    "Emacs Manuals Are Cryptic and Surreal"
			    "Energetic Merchants Always Cultivate Sales"
			    "Each Manual's Audience is Completely Stupified"
			    "Emacs Means A Crappy Screen"
			    "Eventually Munches All Computer Storage"
			    "Even My Aunt Crashes the System"
			    "Eradication of Memory Accomplished with Complete Simplicity"
			    "Elsewhere Maybe Alternative Civilizations Survive"
			    "Egregious Managers Actively Court Stallman"
			    "Esoteric Malleability Always Considered Silly"
			    "Emacs Manuals Always Cause Senility"
			    "Easily Maintained with the Assistance of Chemical Solutions"
			    "EMACS MACRO ACTED CREDO SODOM"
			    "Edwardian Manifestation of All Colonial Sins"
			    "Generally Not Used Except by Middle Aged Computer Scientists"
			    "Extended Macros Are Considered Superfluous"
			    "Every Mode Accelerates Creation of Software"
			    "Elsewhere Maybe All Commands are Simple"
			    "Emacs May Allow Customized Screwups"
			    "Excellent Manuals Are Clearly Suppressed"
			    "Emetic Macros Assault Core and Segmentation"
			    "Embarrassed Manual-Writer Accused of Communist Subversion"
			    "Extensibility and Modifiability Aggravate Confirmed Simpletons"
			    "Emacs May Annihilate Command Structures"
			    "Easily Mangles, Aborts, Crashes and Stupifies"
			    "Extraneous Macros And Commands Stink"
			    "Exceptionally Mediocre Algorithm for Computer Scientists"
			    "EMACS Makes no Allowances Considering its Stiff price"
			    "Equine Mammals Are Considerably Smaller"
			    "Embarrassingly Mundane Advertising Cuts Sales"
			    "Every Moron Assumes CCA is Superior"
			    "Exceptionally Mediocre Autocratic Control System"
			    "EMACS May Alienate Clients and Supporters"
			    "Excavating Mayan Architecture Comes Simpler"
			    "Erasing Minds Allows Complete Submission"
			    "Every Male Adolescent Craves Sex"
			    "Elephantine Memory Absolutely Considered Sine que non"
			    "Emacs Makers Are Crazy Sickos"
			    "Eenie-Meenie-Miney-Mo- Macros Are Completely Slow"
			    "Experience the Mildest Ad Campaign ever Seen"
			    "Emacs Makefiles Annihilate C- Shells"
			    "Eradication of Memory Accomplished with Complete Simplicity"
			    "Emetic Macros Assault Core and Segmentation"
			    "Epileptic MLisp Aggravates Compiler Seizures"
			    "Eleven thousand Monkeys Asynchronously Crank out these Slogans"
			    )))
    (nth (random (1- (1+ (length list)))) list)))
